[Hactoberfest] Fail the execution at the end if any test failures
jenkinsci/docker pull request #1011
Opened 2020-10-31 18:28 UTC by v1v

Closes https://github.com/jenkinsci/docker/issues/1009

### What

Fail the build if any test failures happened when running the windows tests.

It does not fail fast to be able to provide as many details as possible.

### Why

It does not fail if test failures at the moment

2020-10-31 18:33 UTC, MarkEWaite approved these changes
Seems very reasonable to me.  @slide is the expert on this area, along with possible help from @garethjevans

2020-10-31 19:02 UTC, slide requested changes

2020-10-31 19:02 UTC, slide commented on make.ps1
> +            testFailed = 1
Missing $?

2020-10-31 19:02 UTC, slide commented on make.ps1
> +                testFailed = 1
Missing $?

2020-10-31 19:09 UTC, v1v commented
I'm testing whether https://github.com/jenkinsci/docker/pull/1011/commits/3d0820fa40c11b58290daf4eeaf0885a40b6e5ae will fail as expected

2020-10-31 22:31 UTC, v1v commented
Unfortunately I don't own any windows computer, so I'm testing it whether this change works as expected,  it seems it works in my mind, sorry about this iterations

2020-10-31 22:35 UTC, slide commented on make.ps1
> +                $testFailed = 1
You could also use $true and $false instead of 1 and 0, but that is not required.

2020-10-31 23:35 UTC, v1v commented on make.ps1
> +            if ("Failed" -eq $r.Result) {
See https://github.com/pester/Pester/blob/3c1b60138c1cde3a51c8db333de41a3920422fe1/test.ps1/#L139-L142

2020-11-03 16:31 UTC, v1v commented
I was forced to push another commit since the GH UI merge conflicts changed the EOL:
- https://github.com/jenkinsci/docker/commit/2e76727f466cb03075a033b91f730bd242698e89#diff-8876131e1b9638758221a09dbc928ac5e989b22a4cad16f925cf0b5f27477d53

2020-11-10 14:04 UTC, slide approved these changes

2020-11-20 12:38 UTC, merged