feat: add windows images for LTSC 2019
jenkinsci/docker pull request #1020
Opened 2020-11-05 14:47 UTC by garethjevans

2020-11-19 13:33 UTC, slide commented on 11/windows/windowsservercore-2019/openj9/Dockerfile
> +# # set variables to create shared class cache
Is there a reason this part is commented out? It creates a class cache that makes subsequent start-ups faster.

2020-11-19 13:57 UTC, garethjevans commented on 11/windows/windowsservercore-2019/openj9/Dockerfile
> +# # set variables to create shared class cache
only cause they were originally commented out in the image that I copied - https://github.com/jenkinsci/docker/blob/c151d909879755d18246bca514ec8ce620499633/11/windows/windowsservercore-1809/openj9/Dockerfile#L66-L76

2020-11-19 13:57 UTC, garethjevans commented on 11/windows/windowsservercore-2019/openj9/Dockerfile
> +# # set variables to create shared class cache
Would be happy to uncomment them both if you think it would help?

2020-11-19 14:04 UTC, slide commented on 11/windows/windowsservercore-2019/openj9/Dockerfile
> +# # set variables to create shared class cache
Yes, that would be good. Thanks!

2020-11-20 08:38 UTC, daniel-beck requested changes

2020-11-20 08:38 UTC, daniel-beck commented on Jenkinsfile
> +        timeout(time: 100, unit: 'MINUTES') {
No. Just no.

During a security release, I need to wait for the images to be able to ensure ci.jenkins.io is protected before I publish the advisory and push sources (and tests with sample exploits). Parallelize this or or something, but this increasingly taking forever is simply not OK.

2020-11-20 08:39 UTC, daniel-beck commented
I would like to see the data that says there's even a single user for each of the images you're adding here. I suspect there is not.

2020-11-20 15:36 UTC, slide commented
> I would like to see the data that says there's even a single user for each of the images you're adding here. I suspect there is not.

In order to run on Google Cloud, Windows docker images have to be at least 1909. We have received requests to run on Google Cloud, so that is where this is coming from. We could probably reduce to just jdk11 and so forth to reduce the amount of time it takes.

2020-11-20 15:53 UTC, daniel-beck commented
> In order to run on Google Cloud, Windows docker images have to be at least 1909.

So this could replace the 1809 with 2019, easy. We'd just end up in another #1033 if we keep things around forever.

2020-11-20 19:24 UTC, slide commented
not necessarily containers work a little differently on Windows sometimes you need the actual version of Windows that you're running on to be able to use a container

2020-11-20 20:02 UTC, slide commented
I would like to propose that we follow something similar to what Adoptium (the artiest formerly known as AdoptOpenJDK). We should have a small set of "official" images that we publish that are the ones that you would need to worry about for security releases and other "unofficial" images that you don't. I'll start a topic about this with the platform SIG.

2020-11-20 20:44 UTC, daniel-beck commented
> I would like to propose that we follow something similar to what Adoptium (the artiest formerly known as AdoptOpenJDK). We should have a small set of "official" images that we publish that are the ones that you would need to worry about for security releases and other "unofficial" images that you don't. I'll start a topic about this with the platform SIG.

That seems like an interesting approach. Thank you for taking this on!

Don't we have a weird blueocean image around somewhere that would clearly be unofficial?

2020-11-20 21:04 UTC, slide commented
Yes, there is a blue ocean image that is old and not maintained that could possibly be in that category

2020-11-20 21:09 UTC, MarkEWaite commented
The blueocean image was used by the "Installing Docker" instructions on
jenkins.io and by three tutorials on jenkins.io until Vlad Silverman's pull
request to use the jenkins/jenkins images about a month ago.

It is not maintained but as far as I know, it is kept current by automated
processes that use the most recent LTS and the most recent Blue Ocean
plugin releases.

I believe the blueocean image should be officially declared "deprecated"
now that we have install instructions and tutorials dependencies fixed to
use jenkins/jenkins instead of the blueocean image.

On Fri, Nov 20, 2020 at 4:04 PM Alex Earl <notifications@github.com> wrote:

> Yes, there is a blue ocean image that is old and not maintained that could
> possibly be in that category
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/docker/pull/1020#issuecomment-731406367>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABGIDLIHFG26ULZCUXS7ZTSQ3KWFANCNFSM4TLOPXJA>
> .
>

2020-11-20 22:51 UTC, slide commented
FYI, I am adding 20H2 images for Adoptium. 

https://github.com/AdoptOpenJDK/openjdk-docker/pull/472

2020-11-23 12:32 UTC, garethjevans commented
@slide 2019 ltsc also appears to be supported on Google Cloud - https://cloud.google.com/compute/docs/images/os-details#windows_server

2020-11-23 15:53 UTC, slide commented
I think we can reduce this to just one added image if we just provide a jdk11 hotspot image instead of all four variants. Thoughts?

2020-11-23 16:10 UTC, garethjevans commented
This is only "jdk11 hotspot" at the moment, I've removed the other images

2020-11-23 16:34 UTC, slide approved these changes

2020-11-23 16:58 UTC, slide commented
@daniel-beck Are you ok adding this image since we actually reduced the number of windows images with my other PR? We would be at two images instead of four if we merge this. I will also look at parallelizing the Windows builds like we have for the Linux side.

2020-12-03 12:09 UTC, daniel-beck commented
Is this even being built? I just see a file added, are we iterating over directories for this?

2020-12-03 13:18 UTC, slide commented
> Is this even being built? I just see a file added, are we iterating over directories for this?

Yes, it is being built. The make.ps1 file finds all the Windows Dockerfiles and builds them. See https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1020/98/pipeline/28#step-29-log-169 for instance.

2020-12-04 15:20 UTC, slide commented
@daniel-beck  We've reduced the number of Windows builds, are you ok with merging this? This would bring us to 2 when we had 4 before. You have "Changed Requested" in your review and I would like to move forward with this.

2020-12-07 13:32 UTC, merged

2021-01-13 14:21 UTC, daniel-beck commented on 11/windows/windowsservercore-2019/hotspot/Dockerfile
> +FROM jenkins4eval/openjdk:11-hotspot-windowsservercore-ltsc2019
Why are we pretending that `jenkins4eval` is "unofficial" if we end up just repackaging it into `jenkins` images?

2021-01-14 08:47 UTC, garethjevans commented on 11/windows/windowsservercore-2019/hotspot/Dockerfile
> +FROM jenkins4eval/openjdk:11-hotspot-windowsservercore-ltsc2019
@daniel-beck these images are not yet published by AdoptOpenJDK, there is an open PR for this but we've had little progress in getting it merged.  When AdoptOpenJDK start supporting these base images we can remove these.

Would you prefer these were published under a different org? I'm not entirely sure what you are recommending here.

For reference - https://github.com/AdoptOpenJDK/openjdk-docker/pull/365