fix: use the creds in config.json when publishing images
jenkinsci/docker pull request #1038
Opened 2020-11-20 13:41 UTC by garethjevans

2020-11-20 14:42 UTC, slide requested changes
We had something like this before and it caused issues because of the credentials on the ci server.

2020-11-20 17:48 UTC, slide commented
I think this should have a flag involved if you want wanting to use this script from your own system. I don't think we should merge this as is.

2020-11-22 11:49 UTC, garethjevans commented
This was based on the current master failures of:

```
./.ci/publish-tags.sh: line 30: DOCKERHUB_USERNAME: unbound variable
```

I took a look at the other scripts in the `.ci` folder and they all seem to use this method of authenticating.

2020-11-22 12:32 UTC, olblak commented
wouldn't it be easier to set DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD on ci.j.io and trusted.ci? at the moment we use a config.json

2020-11-22 16:05 UTC, slide commented
The publish-tags script needs to be fixed to not do this.

2020-11-23 09:23 UTC, garethjevans commented
@olblak @slide happy to go with whatever you think is best.  I can change this PR to use the variables if you think thats best

2020-11-23 15:31 UTC, slide commented
We already have DOCKER_CONFIG being set on ci.j.io and trusted. So, I think this `docker login` call should be wrapped with a check if DOCKER_CONFIG is empty or not set.

https://github.com/jenkins-infra/pipeline-library/blob/5b6efab292955b7cd73760a4cc9d4546f5f50525/vars/infra.groovy#L18

2020-12-03 23:16 UTC, slide commented on .ci/publish-images.sh
> +      docker login
I don't think we want this at all, I believe docker will automatically look for DOCKER_CONFIG and use it.

2020-12-04 09:06 UTC, garethjevans commented
@olblak @slide I'm going to close this PR until we can get some consensus on a way forward.

2020-12-04 09:06 UTC, closed without merging