install-plugins uses JENKINS_UC_DOWNLOAD if specified
jenkinsci/docker pull request #1299
Opened 2022-03-07 23:05 UTC by nhojpatrick

To speed up testing plugins I setup a local web server with the plugins I was using. So I tried to get JENKINS_UC_DOWNLOAD working. Due to the current logic, if you specify JENKINS_UC_DOWNLOAD, it doesn't ever get used as JENKINS_UC_LATEST will get set 1st and always used.

Taking this example Dockerfile;

```
FROM jenkins/jenkins:lts
ENV JENKINS_UC_DOWNLOAD https://updates.jenkins.io/download
RUN /usr/local/bin/install-plugins.sh  greenballs
```

The current version will download from `https://updates.jenkins.io/dynamic-2.319//latest/greenballs.hpi`

The patched version will download from `https://updates.jenkins.io/download/plugins/greenballs/latest/greenballs.hpi`

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-03-07 23:56 UTC, MarkEWaite commented
I'd much rather that people switch to use the plugin installation manager tool (wrapped in the `jenkins-plugin-cli.sh` file) rather than make changes to the install-plugins.sh script.  The script is deprecated and lacks features that are available in the replacement.

2022-03-08 08:33 UTC, timja requested changes
We only accept changes to this script if it's broken.

Please switch to the plugin manager cli https://github.com/jenkinsci/plugin-installation-manager-tool

https://github.com/jenkinsci/docker/blob/4fe20c4c8bfe28b69322640082f594cebaf6edb1/install-plugins.sh#L23

2022-03-08 13:34 UTC, nhojpatrick commented
I'm using a jenkins image provided by [openshift](https://github.com/openshift/jenkins) and `jenkins-plugin-cli` is not packaged/avaliable but `install-plugins.sh` is. Also do most builds via openshift so never actually saw that WARN before your comment above.

For my reference where is `jenkins-plugin-cli.sh/ps1` maintainered? So if submit a pr for RedHat, I point them to the root source to include in the offerings.

2022-03-08 13:40 UTC, timja commented
Wrapper script:
https://github.com/jenkinsci/docker/blob/master/jenkins-plugin-cli.sh

Sources:
https://github.com/jenkinsci/plugin-installation-manager-tool

2022-03-08 20:12 UTC, nhojpatrick commented
Thanks for details @timja will see if I can sort out OpenShift's image stream.

2022-03-08 20:12 UTC, closed without merging