Remove install-plugins.sh
jenkinsci/docker pull request #1408
Opened 2022-06-25 22:09 UTC by timja

install-plugins.sh was deprecated in September of 2020 (https://github.com/jenkinsci/docker/pull/986)

All references to it in documentation were removed in https://github.com/jenkinsci/docker/pull/1302
jenkins.io does not use install-plugins.sh, the only non blog post reference is being removed in https://github.com/jenkins-infra/jenkins.io/pull/5256

It's causing maintenance problems with an unstable test suite preventing us from merging PRs in currently. (https://github.com/jenkinsci/docker/pull/1407)

----

In early 2021 there was a proposal to create a shim (https://github.com/jenkinsci/docker/pull/1073) and transparently move people across.

That may work but then we would be stuck maintaining that shim, and likely there would be compatibility problems with edgecases along with issues like proxies and behaviour that people have set through flags that are specific to curl and they would end up with behaviour changes.

----

People who do not want to move are welcome to fetch the script at the last revision here https://github.com/jenkinsci/docker/blob/a9de6b9fb3a0601e51321bc0ea8c7638db2bf88f/install-plugins.sh

----

I've kept the script telling people what to do to migrate in the Java 11 images
I've removed it in Java 17, as it's very unlikely that the few early adopters are using the script to manage plugins. We will not add the script in new images and will remove it from older images at some point

2022-06-25 23:10 UTC, MarkEWaite commented
Thanks very much for the pull request.  I think that it is exactly the right thing to do.  This is also a good opportunity for me to complete my long-standing action item from the Docs Office Hours to include more use case descriptions in the plugin installation manager tool documentation.

2022-06-26 07:14 UTC, dduportal requested changes
I'm all in favor to remove this script `install-plugins.sh`, that would help a lot \o/

However can you restore the directory `tests/upgrade-plugins` ? It is used by the test harness for the plugins-cli, and it's failing the checks for this PR:

```console
# mktemp: failed to create file via template ‘/home/jenkins/workspace/Packaging_docker_PR-1408/tests/upgrade-plugins/Dockerfile.XXXXXX’: No such file or directory
#   /home/jenkins/workspace/Packaging_docker_PR-1408/tests/test_helpers.bash: line 77: : No such file or directory
#   unable to prepare context: path "/home/jenkins/workspace/Packaging_docker_PR-1408/tests/upgrade-plugins" not found
#   rm: cannot remove '': No such file or directory
```

2022-06-26 07:32 UTC, timja commented
> However can you restore the directory tests/upgrade-plugins ? It is used by the test harness for the plugins-cli, and it's failing the checks for this PR:

No need to request changes over a test failure, it will be fixed before integrating.

I was just running them locally after updating the Dockerfile :)

2022-06-26 08:32 UTC, dduportal approved these changes

2022-06-26 08:37 UTC, merged