chore(dependencies): Updatecli manifests for java
jenkinsci/docker pull request #1711
Opened 2023-09-18 08:40 UTC by gounthar

After @MarkEWaite 's comment on PR #1707 (and subsequent PR #1710), I propose three manifests to track the JDK versions.
I have created three `updatecli` manifests for JDK11, 17, and 21.

### Testing done

```bash
updatecli diff --config ./updatecli/updatecli.d/jdk11.yaml --values ./updatecli/
values.github-action.yaml --debug
 updatecli diff --config ./updatecli/updatecli.d/jdk17.yaml --values ./updatecli/
values.github-action.yaml --debug
 updatecli diff --config ./updatecli/updatecli.d/jdk21.yaml --values ./updatecli/
values.github-action.yaml --debug
```

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- ~~Link to relevant issues in GitHub or Jira~~
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-09-19 17:09 UTC, gounthar commented
Last build failed, but I'm not so sure it's my fault:

```
ERROR: failed to solve: process "/bin/sh -c curl -fsSL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war   && echo \"${JENKINS_SHA}  /usr/share/jenkins/jenkins.war\" >/tmp/jenkins_sha   && sha256sum -c --strict /tmp/jenkins_sha   && rm -f /tmp/jenkins_sha" did not complete successfully: exit code: 22
[1299](https://ci.jenkins.io/job/Packaging/job/docker/job/PR-1711/11/pipeline-console/?start-byte=296974&selected-node=858#log-1299)
script returned exit code 1
```

2023-09-23 17:26 UTC, dduportal commented on 21/alpine/hotspot/Dockerfile
> +  && BUILD_NUMBER=$(echo $JAVA_VERSION | cut -d'+' -f2) \
I believe you also have to remove the `BUILD_NUMBER` ARG and inline the default value in the JAVA_VERSION WDYT?

eg

```
ARG JAVA_VERSION=21+35
```

instead of 

```
ARG BUILD_NUMBER=35
ARG JAVA_VERSION=21+${BUILD_NUMBER}
```

2023-09-23 17:26 UTC, dduportal commented on 21/debian/bookworm-slim/hotspot/Dockerfile
> +  && BUILD_NUMBER=$(echo $JAVA_VERSION | cut -d'+' -f2) \
Same as https://github.com/jenkinsci/docker/pull/1711/files#r1335046154

2023-09-23 17:27 UTC, dduportal commented on 21/debian/bookworm/hotspot/Dockerfile
> +  && BUILD_NUMBER=$(echo $JAVA_VERSION | cut -d'+' -f2) \
Same as https://github.com/jenkinsci/docker/pull/1711/files#r1335046154

2023-09-23 17:27 UTC, dduportal commented on 21/rhel/ubi9/hotspot/Dockerfile
> +  && BUILD_NUMBER=$(echo $JAVA_VERSION | cut -d'+' -f2) \
Same as https://github.com/jenkinsci/docker/pull/1711/files#r1335046154

2023-09-23 17:54 UTC, gounthar commented on 21/alpine/hotspot/Dockerfile
> +  && BUILD_NUMBER=$(echo $JAVA_VERSION | cut -d'+' -f2) \
Yes, for sure.
I was thinking of doing that in a later PR, but that does not really make sense. 🤷 
Let me correct that.

2023-09-23 18:34 UTC, dduportal requested changes
The updatecli manifests look really good.

But we have to, first, work on #1710 to avoid PR with double quotes 😅 

Blocking until #1710 is merged and it is rebased (with conflict merges) here

2023-09-23 21:15 UTC, dduportal reviewed
- Don't forget https://github.com/jenkinsci/docker/pull/1710#issuecomment-1723276924 (removing dependabot JDK tracking in favor of updatecli)
- Looks like we forgot to update the Windows dockerfiles in #1710 : worth another (tiny) PR if we want updatecli to work properly in this PR

2023-09-24 16:49 UTC, gounthar commented
Thank you Damien.

> * Looks like we forgot to update the Windows dockerfiles in [chore(dependencies): Preliminary work to integrate `updatecli`. #1710](https://github.com/jenkinsci/docker/pull/1710) : worth another (tiny) PR if we want updatecli to work properly in this PR

Strangely, I had done it in #1711...
That is corrected through #1720 .

2023-09-24 17:03 UTC, gounthar commented
Following [this comment](https://github.com/jenkinsci/docker/pull/1710#issuecomment-1723276924), I tried to remove the dependabot work about Java.

2023-09-24 20:03 UTC, dduportal commented
One last time: as we discussed last week let's roll back the updatecli manifest to use `ARG` instead of `FROM`.

Rationale is that, even if the initial proposal to use `FROM` looked simpler, we want to use the Docker Bake  to specify the JAVA_VERSION so `ARG` is mandatory.
The idea is to, like for agents, to [Remove the `ARG` default value](https://github.com/jenkinsci/docker-agent/issues/418).

2023-09-25 16:54 UTC, dduportal approved these changes
```
Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	0
  * Skipped:	0
  * Succeeded:	4
  * Total:	4
```

Nice work 👏

2023-09-25 16:54 UTC, merged