Improve logging for common failure when using default config
jenkinsci/docker pull request #1801
Opened 2023-12-29 12:25 UTC by clintonsteiner

- Improve user guidance for JENKINS_HOME permission issues by adding detailed warning message if USER lacks rw access
- Took me a few minutes to resolve this, and saw quite a few so threads of people running into the same issue
- installing the docker container onto unRaid led me into this error touch: cannot touch '/var/jenkins_home/copy_reference_file.log' Accompanied by the application failing to launch

### Testing done
Tested by validating logging for permission failure again as well as testing negative case where logging didnt appear with correct permissions

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-01-02 22:18 UTC, saper commented on jenkins.sh
> +if ! $([ -r "$JENKINS_HOME" ] && [ -w "$JENKINS_HOME" ]); then
I'd do `if ! [ -r "${JENKINS_HOME}" -a -w "${JENKINS_HOME}" ]; then` here (one external command only, no subshell).

2024-01-02 22:21 UTC, saper commented on jenkins.sh
> +fi
does it make sense to continue here at all?

2024-01-02 22:29 UTC, clintonsteiner commented on jenkins.sh
> +fi
Good question, probably not?

2024-01-02 22:35 UTC, clintonsteiner commented on jenkins.sh
> +fi
Added exit

2024-01-02 22:35 UTC, clintonsteiner commented on jenkins.sh
> +if ! $([ -r "$JENKINS_HOME" ] && [ -w "$JENKINS_HOME" ]); then
Thanks for the suggestion. Done

2024-01-03 09:02 UTC, dduportal requested changes
Thanks! It looks like a really useful addon to help users with their storage issues, many thanks!

I've got 2 suggestions related to the lint failures happening in ci.jenkins.io but it is almost ready to go!

2024-01-03 09:02 UTC, dduportal commented on jenkins.sh
> +if ! [ -r "${JENKINS_HOME}" -a -w "${JENKINS_HOME}" ]; then
```suggestion
if ! [ -r "${JENKINS_HOME}" ] && [ -w "${JENKINS_HOME}" ]; then
```

The static analysis with [shellcheck](https://www.shellcheck.net/) fails on this line with the following error:

```text
if ! [ -r "${JENKINS_HOME}" -a -w "${JENKINS_HOME}" ]; then
                                                ^-- SC2166 (warning): Prefer [ p ] && [ q ] as [ p -a q ] is not well defined.
```

=> My suggestion above keeps the same behavior as proposed by @saper earlier in this PR (e.g. no double subshell) while following shellcheck recommendation (less ambiguity due to shell operators)

2024-01-03 09:02 UTC, dduportal commented on jenkins.sh
> +    exit -1;
```suggestion
    exit 1;
```

The static analysis with [shellcheck](https://www.shellcheck.net/) fails on this line with the following error:

```text
exit -1;
       ^-- SC2242 (error): Can only exit with status 0-255. Other data should be written to stdout/stderr.
```


=> Exit code must be between 0 and 255 as per https://tldp.org/LDP/abs/html/exitcodes.html

2024-01-03 17:22 UTC, clintonsteiner commented
@dduportal updated the pr! Thank you for the suggested changes!

2024-01-04 06:42 UTC, dduportal approved these changes

2024-01-04 06:44 UTC, dduportal commented
Hello @basil @timja , I would be interested by a review from one of you (given your shell skills and infra habits) to see if I'm not missing (as @saper and I already revieed).

2024-01-04 07:31 UTC, timja commented on jenkins.sh
> +    exit 1;
Does this need to exit?

I saw this PR recently https://github.com/jenkinsci/cloudbees-disk-usage-simple-plugin/pull/99

where apparently some people run it with a read only file system and mount certain paths

2024-01-04 07:45 UTC, basil commented on jenkins.sh
> +    exit 1;
I saw that too, but I have mixed feelings about supporting it. I definitely would not go out of my way to make it easy for users to do this. Whether or not it should be merely tolerated or rejected outright is a more subjective question.

2024-01-04 07:50 UTC, basil commented on jenkins.sh
> +    exit 1;
From a stylistic point of view, there's no need for the trailing semicolon at the end of each line in a script, and the quoting can be simplified to:

```bash
        echo "INSTALL WARNING: User: ${USER} missing rw permissions on JENKINS_HOME: ${JENKINS_HOME}"
        echo "    Jenkins unable to start. To fix, use chown or setfacl -m u:${USER}:rwx ${JENKINS_HOME}"
```

I personally support the (strict) behavior of rejecting such a configuration and failing fast. But if this is too harsh, I could see the other perspective of merely tolerating such a configuration and printing a (soft) warning.

2024-01-04 20:27 UTC, clintonsteiner commented on jenkins.sh
> +    exit 1;
I had left it, but different review asked the question if there was a reason to continue.
Not seeing one, I added an exit.

I'll leave that up the maintainers to decide one way or another

2024-01-04 20:28 UTC, clintonsteiner commented on jenkins.sh
> +    exit 1;
Is the environment variable way the one we'd like to implement?

2024-01-04 20:31 UTC, clintonsteiner commented on jenkins.sh
> +    exit 1;
Simplified

2024-01-04 20:31 UTC, clintonsteiner commented on jenkins.sh
> +    exit 1;
Removed the exit, I can add it back in if that is desired

2024-01-04 20:41 UTC, saper commented on jenkins.sh
> +    exit 1;
@clintonsteiner big thank you for your patience with this!

> Jenkins unable to start. To fix, use chown or setfacl 

If we don't exit, and we support read-only JENKINS_HOME with writable subdirectories (however strange it might be), we should not say "unable to start".

In my practice very often permission problems are also related to file systems mounted read-only, so "chown/setfacl" does not apply there.

Shall we just drop that second line?

2024-01-04 20:52 UTC, clintonsteiner commented on jenkins.sh
> +    exit 1;
Yeah that works for me, I ran into this issue installing it on via unraid template and wanted to offer improved troubleshooting for the next person.

I will drop the second line and squash momentarily

2024-01-04 20:55 UTC, clintonsteiner commented on jenkins.sh
> +    exit 1;
Squashed. Thank you everyone! @saper

2024-01-04 21:05 UTC, saper approved these changes

2024-01-04 21:37 UTC, saper requested changes

2024-01-04 21:37 UTC, saper commented on jenkins.sh
> +if ! [ -r "${JENKINS_HOME}" ] && [ -w "${JENKINS_HOME}" ]; then
Oh, I have just tested this like this:

```
> chmod a+rwx testdir/* 2>/dev/null; rm -rf testdir && install -d -m 000 testdir/nr && install -d -m 222 testdir/wr && install -d -m 555 testdir/ro && install -d -m 755 testdir/rw; for i in testdir/*; do echo "$i"; if ! [ -r "$i" ] &&  [ -w "$i" ]; then echo "unreadable or not writable"; else echo "no warning"; fi; done
chmod a+rwx testdir/* 2>/dev/null; rm -rf testdir && install -d -m 000 testdir/nr && install -d -m 222 testdir/wr && install -d -m 555 testdir/ro && install -d -m 755 testdir/rw; for i in testdir/*; do echo "$i"; if ! [ -r "$i" ] &&  [ -w "$i" ]; then echo "will print warning"; else echo "no warning"; fi; done
testdir/nr
no warning
testdir/ro
no warning
testdir/rw
no warning
testdir/wr
will print warning
```

this works better:

```
> chmod a+rwx testdir/* 2>/dev/null; rm -rf testdir && install -d -m 000 testdir/nr && install -d -m 222 testdir/wr && install -d -m 555 testdir/ro && install -d -m 755 testdir/rw; for i in testdir/*; do echo "$i"; if ! [ -r "$i" ] || ! [ -w "$i" ]; then echo "will print warning"; else echo "no warning"; fi; done
testdir/nr
will print warning
testdir/ro
will print warning
testdir/rw
no warning
testdir/wr
will print warning
```

So shall we have this instead?
```
if ! [ -r "${JENKINS_HOME}" ] || ! [ -w "${JENKINS_HOME}" ]; then
```

2024-01-04 21:39 UTC, saper commented on jenkins.sh
> +if ! [ -r "${JENKINS_HOME}" -a -w "${JENKINS_HOME}" ]; then
Looks like this introduces a bug... :/

2024-01-04 21:45 UTC, clintonsteiner commented on jenkins.sh
> +if ! [ -r "${JENKINS_HOME}" ] && [ -w "${JENKINS_HOME}" ]; then
Fixed and squashed again

2024-01-04 21:48 UTC, saper approved these changes

2024-01-04 22:51 UTC, clintonsteiner commented
Ready to merge, would someone with write access please do the honors?

2024-01-04 23:09 UTC, merged

2024-01-04 23:09 UTC, timja commented
Thanks, to be clear I was happy about the exit. I wasn't asking for it to be removed, but possibly adding an opt-out, but this is still fine.