chore(updatecli): Check the validity of releases thanks to the Adoptium API.
jenkinsci/docker pull request #1851
Opened 2024-04-17 19:30 UTC by gounthar

This is a follow-up to #1847, not to be merged before it, as it enhances one shell script.

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-04-19 14:56 UTC, gounthar commented
I won't be available to work on this PR until April 30th, so feel free to merge, modify, close, or take any other necessary action.

2024-04-20 20:56 UTC, MarkEWaite requested changes
I wasn't able to make the comma separated ARCHS arguments work in my testing on Ubuntu 22.04.  When I used a space separator between the values, it worked as expected.

2024-04-20 20:56 UTC, MarkEWaite commented on updatecli/updatecli.d/jdk17.yaml
> +      command: sh ./jdk-download-url.sh '{{source "lastVersion" }}' standard "x64,aarch64,s390x"
In my interactive testing, it worked better for me when I used space separators between the values of the third argument rather than using comma separators.  I inserted debugging print statements and confirmed that I had the correct results when I ran:

```
./jdk-download-url.sh 11.0.23+9 standard "aarch64 x64"
```


```suggestion
      command: sh ./jdk-download-url.sh '{{source "lastVersion" }}' standard "x64 aarch64 s390x"
```

2024-04-20 20:56 UTC, MarkEWaite commented on updatecli/updatecli.d/jdk21.yaml
> +      command: sh ./jdk-download-url.sh '{{source "lastVersion" }}' standard "x64,aarch64,s390x"
Same result here as mentioned earlier.  It worked better for me in my interactive testing when I used a space separator between the ARCHS values rather than using a "," separator.
```suggestion
      command: sh ./jdk-download-url.sh '{{source "lastVersion" }}' standard "x64 aarch64 s390x"
```

2024-04-20 20:56 UTC, MarkEWaite commented on updatecli/updatecli.d/jdk11.yaml
> +      command: sh ./jdk-download-url.sh '{{source "lastVersion" }}' standard "x64,aarch64,s390x"
See other comments about comma separator instead of space separator
```suggestion
      command: sh ./jdk-download-url.sh '{{source "lastVersion" }}' standard "x64 aarch64 s390x"
```

2024-04-21 22:02 UTC, MarkEWaite approved these changes
Approved based on the change that I applied to switch from comma separated items in the ARCHS value to space separated.

2024-04-22 03:58 UTC, merged