Document skipping initial setup wizard
jenkinsci/docker pull request #833
Opened 2019-06-06 07:21 UTC by ringerc

Documented steps to skip setup wizard didn't appear to work on `jenkins/jenkins:latest`  or `jenkins/jenkins:latest`. Neither did variants of them that tried to cope with volume-mounting etc, like:

```
RUN echo $JENKINS_VERSION | tee \
    /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state \
    /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion
```

Instead, recommend use of a system property that is known to work.

2019-06-06 07:26 UTC, oleg-nenashev commented on README.md
> +Note: Some documentation suggested creating `jenkins.install.UpgradeWizard.state` and/or `jenkins.install.InstallUtil.lastExecVersion`. Using the system property is simpler and more reliable.
it is

2019-06-06 07:27 UTC, oleg-nenashev commented on README.md
> +This will disable creation of the default admin user and password, and will leave Jenkins in an unsecured configuration where anyone who can connect has full admin rights. So it should generally be c
```suggestion
Unless you use some kind of Configuration-as-Code to configure the instance (Groovy Hooks, JCasC plugin, etc.), 
this will disable creation of the default admin user and password, and will leave Jenkins in an unsecured configuration where anyone who can connect has full admin rights. So it should generally be coupled with automation to install plugins and to configure the server.
```

2019-06-06 07:28 UTC, oleg-nenashev commented on README.md
> +## Applying an initial server configuration
Maybe it worth referencing https://speakerdeck.com/onenashev/docker-and-jenkins-as-code or a similar slidedeck

2019-06-06 07:34 UTC, daniel-beck commented on README.md
> +This will disable creation of the default admin user and password, and will leave Jenkins in an unsecured configuration where anyone who can connect has full admin rights. So it should generally be c
Additionally, several other security-related settings will not be enabled by default. While I don't think we should provide an exhaustive list that might easily become outdated, it's important to point this out.

2019-06-06 07:34 UTC, daniel-beck commented
> Documented steps

FWIW the "documented" (in this repo only) steps have always been an unsupported hack and I don't understand how they became preferable over the supported method. Perhaps because it didn't require changing how to invoke `docker`?

2021-03-16 13:54 UTC, NorseGaud commented
None of the proposed methods work with the latest LTS (2.7)

2021-03-16 14:59 UTC, slide commented
@NorseGaud Are you referring to 2.277.1?

2021-03-16 15:47 UTC, NorseGaud commented
@slide Yep -- it seems like `JAVA_OPTS="-Djenkins.install.runSetupWizard=false"` when launching lts tag from docker has no impact and the admin password wizard/login still shows. Maybe I'm misunderstanding.

2023-08-03 13:29 UTC, whoami-anoint requested changes

2023-08-03 13:29 UTC, whoami-anoint commented on README.md
>  COPY custom.groovy /usr/share/jenkins/ref/init.groovy.d/custom.groovy
```suggestion
```dockerfile
FROM jenkins/jenkins:lts
COPY custom.groovy /usr/share/jenkins/ref/init.groovy.d/custom.groovy
```
```

2023-08-03 13:34 UTC, whoami-anoint approved these changes

2025-05-06 07:01 UTC, closed without merging

2025-05-06 07:01 UTC, dduportal commented
I'm proceeding with closing this PR because the initial problem is fixed since quite some time.

I'm using the currently documented technique in https://github.com/dduportal/jenkins-examples/blob/e67bdab89354ea85ebf09131459af9f037b5a5c6/docker-image/Dockerfile#L4 and it works as expected (and had worked for the past 5 years).