[docker] support metadata labels
jenkinsci/docker pull request #965
Opened 2020-07-01 16:06 UTC by v1v

It uses the metadata labels format explained in https://microbadger.com/labels

2020-07-02 15:44 UTC, slide commented on Dockerfile
> +    org.label-schema.vendor="Jenkins project" \
Would we want "Jenkins Project" with a capital P?

2020-07-02 16:08 UTC, v1v commented on Dockerfile
> +    org.label-schema.vendor="Jenkins project" \
No strong opinion I used the one already defined in https://github.com/jenkinsci/docker-agent/pull/141/files#diff-77057272bfe150be8f21c133d8797affL33, so if capital P then I'll change the other PR

2020-07-02 16:27 UTC, slide commented on Dockerfile
> +    org.label-schema.vendor="Jenkins project" \
I don't have a strong opinion either and I just noticed that from docker-agent as well. We can always change it to capital P later if desired.

2020-09-16 09:42 UTC, v1v commented
🙏 Is there anything else to get this merged? Thanks

2020-09-16 15:44 UTC, slide commented on Makefile
> +	docker build --build-arg BUILD_DATE=$(BUILD_DATE) --file Dockerfile .
Just as an FYI, this would not be used until we move builds to our own infra. The Dockerhub builds don't allow setting build args from what I can see.

2020-10-15 20:10 UTC, oleg-nenashev requested changes
We need to resolve the merge conflict :(

2020-10-15 20:11 UTC, slide commented
Also, just to reiterate, the BUILD_DATE will not be set unless we move Linux image building/publishing to our own infra from Dockerhub builds.

2020-10-28 19:49 UTC, v1v commented
I just merged and fixed the conflicts. In addition, I removed the BUILD_DATE https://github.com/jenkinsci/docker/pull/965/commits/db75ddc034b51923e43379da30403748b7dcf1ef

2020-10-28 22:18 UTC, slide approved these changes

2020-10-31 13:09 UTC, v1v commented on tests/test_helpers.bash
> +
I've just found I need to reimplement this particular function

2020-11-02 15:57 UTC, slide approved these changes

2020-11-05 16:51 UTC, v1v commented
I think the failed tests are related to https://github.com/jenkinsci/docker/issues/1014

New tests are passing 
![image](https://user-images.githubusercontent.com/2871786/98270643-fa477d80-1f86-11eb-9410-8cb4533d48c2.png)

https://ci.jenkins.io/job/Packaging/job/docker/job/PR-965/492/testReport/C__Jenkins_workspace_Packaging_docker_PR-965_tests_runtime.Tests/ps1/Build___windows___Test____11_hotspot_windowsservercore_1809__test_jenkins_arguments_version_in_docker_metadata/

![image](https://user-images.githubusercontent.com/2871786/98270687-04697c00-1f87-11eb-9599-9c5096448536.png)

https://ci.jenkins.io/job/Packaging/job/docker/job/PR-965/492/testReport/jenkinsci.docker.debian/Default/Build___linux___slim___Test_slim____35__8_debian_buster_hotspot__test_version_in_docker_metadata/

2020-11-24 21:24 UTC, v1v commented
Is there anything else missing?

2020-11-24 22:51 UTC, slide commented
Looks like there are some conflicts that need to be resolved

2020-12-07 21:45 UTC, timja commented
@slide?

2020-12-07 21:45 UTC, timja commented
/ @oleg-nenashev

2020-12-07 21:46 UTC, slide commented
Just waiting on Oleg, he had requested changes.

2020-12-08 11:52 UTC, garethjevans commented
@oleg-nenashev are you ok with this?

2021-02-12 17:37 UTC, slide commented
One test failing on the windows side right now.

2021-07-08 07:26 UTC, timja commented
Looks like opencontainers is the replacement: https://github.com/opencontainers/image-spec/blob/master/annotations.md

2021-07-08 07:35 UTC, timja approved these changes

2021-07-09 07:25 UTC, timja commented
@slide any chance you can check the windows failure?

2021-08-02 08:59 UTC, timja approved these changes
Lol the failure was do dumb, a new image was added and it just needed adding to.

🤕

2021-08-02 11:07 UTC, merged