Initial release of quick-start demo solution
jenkinsci/docker pull request #970
Opened 2020-07-27 20:54 UTC by vsilverman

This PR addresses the issue #969

2020-08-03 07:31 UTC, vsilverman commented
Merging of this PR also resolves [jenkins-infra/jenkins.io/#3583](https://github.com/jenkins-infra/jenkins.io/issues/3583)

2020-11-24 21:27 UTC, v1v commented on quick-start/README.md
> +Use the "Select plugins to install" option in the Customize CloudBees Jenkins Distribution screen,  select None in the top panel of the window to unselect all plugins. Then click Install.
Is CloudBees needed in this context?

2020-11-24 22:19 UTC, vsilverman commented on quick-start/README.md
> +Use the "Select plugins to install" option in the Customize CloudBees Jenkins Distribution screen,  select None in the top panel of the window to unselect all plugins. Then click Install.
not in this context, i believe

2020-11-24 22:39 UTC, MarkEWaite requested changes

2020-11-24 22:39 UTC, MarkEWaite commented on quick-start/README.md
> +Use the "Select plugins to install" option in the Customize CloudBees Jenkins Distribution screen,  select None in the top panel of the window to unselect all plugins. Then click Install.
CloudBees Jenkins Distribution was a free product provided by CloudBees.  It is no longer being actively promoted.  We can refer to Jenkins here rather than the CloudBees Jenkins Distribution.
```suggestion
Use the "Select plugins to install" option in the Customize Jenkins screen,  select None in the top panel of the window to unselect all plugins. Then click Install.
```

2022-02-09 23:56 UTC, closed without merging