Update directory structure and use AdoptOpenJDK base images
jenkinsci/docker pull request #985
Opened 2020-09-09 20:12 UTC by slide

Updates the directory structure to follow changes that were made in the agent images. Also, updates to use AdoptOpenJDK as base images instead of OpenJDK. Supersedes #956

2020-09-10 14:26 UTC, MarkEWaite requested changes
We can simplify the install and use the git-lfs provided with the operating system.  It is a new enough version that it does not have the issue we found with Debian stretch

2020-09-10 14:26 UTC, MarkEWaite commented on 8/debian/buster-slim/hotspot/Dockerfile
> +RUN apt-get update && apt-get upgrade -y && apt-get install -y git curl gpg unzip libfreetype6 libfontconfig1 && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | ba
Debian Buster does not need the special case install of git LFS.  Should also not need us to specify libfreetype or libfontconfig
```suggestion
# Install git lfs on Debian stretch per https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu
# Avoid JENKINS-59569 - git LFS 2.7.1 fails clone with reference repository
RUN apt-get update && apt-get upgrade -y && apt-get install -y git git-lfs curl gpg unzip && git lfs install && rm -rf /var/lib/apt/lists/*
```

2020-09-10 15:16 UTC, slide commented on 8/debian/buster-slim/hotspot/Dockerfile
> +RUN apt-get update && apt-get upgrade -y && apt-get install -y git curl gpg unzip libfreetype6 libfontconfig1 && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | ba
Are you sure on the libfreetype? I think those are needed for the AWT stuff even in headless mode.

2020-09-10 15:26 UTC, MarkEWaite commented on 8/debian/buster-slim/hotspot/Dockerfile
> +RUN apt-get update && apt-get upgrade -y && apt-get install -y git curl gpg unzip libfreetype6 libfontconfig1 && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | ba
Good point.  No objection if we retain libfreetype.  I was able to run the image without it, but may be safer to retain it than risk it.

2020-09-17 16:48 UTC, james-crowley requested changes

2020-09-17 16:48 UTC, james-crowley commented on 11/debian/buster-slim/hotspot/Dockerfile
> +FROM adoptopenjdk/openjdk11:debian-slim
As we discussed on Gitter, you probably want to pull from `adoptopenjdk/openjdk8:debianslim-slim` as that is made from the Debian Slim builds. The general `-slim` tag you see is mostly a script AdoptOpenJDK runs to remove unneeded files to reduce the overall image size.

2020-09-18 17:43 UTC, slide commented
@james-crowley I believe I am using the correct images now, can you look?

2020-09-18 18:22 UTC, james-crowley requested changes
Here is more information: https://github.com/AdoptOpenJDK/openjdk-docker#official-and-unofficial-images

2020-09-18 18:22 UTC, james-crowley commented on 11/debian/buster/hotspot/Dockerfile
> +FROM adoptopenjdk:11-hotspot
For official images, it looks like the "default" image is based on Ubuntu not Debian. If your okay with that, you should change the file path to `11/ubuntu/bionic/hotspot/Dockerfile`.

2020-09-18 18:22 UTC, james-crowley commented on 8/debian/buster/hotspot/Dockerfile
> +FROM adoptopenjdk:8-hotspot
For official images, it looks like the "default" image is based on Ubuntu not Debian. If your okay with that, you should change the file path to `8/ubuntu/bionic/hotspot/Dockerfile`.

2020-09-18 18:24 UTC, slide commented on 11/debian/buster/hotspot/Dockerfile
> +FROM adoptopenjdk:11-hotspot
I think we want to stick with debian, so I'll need to update this.

2020-09-18 19:09 UTC, james-crowley commented on 11/debian/buster/hotspot/Dockerfile
> +FROM adoptopenjdk:11-hotspot
So I think you would want to use `adoptopenjdk/openjdk11:debian`.

2020-09-18 19:10 UTC, james-crowley commented on 8/debian/buster/hotspot/Dockerfile
> +FROM adoptopenjdk:8-hotspot
And for this one use `adoptopenjdk/openjdk8:debian`.

2020-09-21 16:26 UTC, slide commented
@MarkEWaite have I addressed your concerns?

2020-09-21 19:25 UTC, MarkEWaite approved these changes
Looks good to me.

2020-09-21 20:38 UTC, merged

2020-09-23 07:14 UTC, timja commented
publish.sh changes were missed here breaking the docker publishing build on trusted

2020-09-23 22:25 UTC, slide commented
I'll fix it up, thanks for the info.