[WIP] Fix Jenkinsfile to build all variants
jenkinsci/docker pull request #998
Opened 2020-10-02 21:28 UTC by slide

This is a work in progress to re-enable publishing of experimental images

2020-10-03 00:46 UTC, MarkEWaite requested changes
Looks good to me with one change for the ppc64le agent that does not connect to ci.jenkins.io

2020-10-03 00:46 UTC, MarkEWaite commented on Jenkinsfile
> +                      'ppe64le' : ['debian', 'slim', 'alpine', 'jdk11']
We'll need to leave this as a comment until we resolve the issue with the ppc64le agent on ci.jenkins.io.
```suggestion
                      // 'ppe64le' : ['debian', 'slim', 'alpine', 'jdk11']
```

2020-10-15 08:03 UTC, olblak approved these changes

2021-07-26 12:25 UTC, timja commented
no longer needed

2021-07-26 12:26 UTC, closed without merging